### ISSUE TITLE
Error rest_invalid_signature trying to refresh orders on iOS

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-ios#1209]
Sometimes (about 1/5 of the time) there is a problem with the API request when the app try to refresh orders. Related issue: https://github.com/woocommerce/woocommerce-ios/issues/916

## Environment:
- Device: iPhone X and simulators
- OS Version: iOS 12.3.1

## Steps to reproduce the behavior:
- It's difficult to reproduce since I don't do any action, I'm waiting to finish refreshing the list. It does not always occur.

## Expected behavior:
- Refresh without errors

## WordPress Environment
<details>
```
Fatal error: Uncaught Error: Call to a member function get_field() on null in /membri/.dummy/master/wordpress/wp-content/plugins/altervista/classes/class-av-themes-manager.php:84 Stack trace: #0 /membri/.dummy/master/wordpress/wp-content/plugins/altervista/classes/class-av-themes-manager.php(125): AV_Themes_Manager::theme_info_for_api(NULL) #1 /membri/wootesting/wp-includes/class-wp-hook.php(286): AV_Themes_Manager::themes_api(false, 'theme_informati...', Object(stdClass)) #2 /membri/wootesting/wp-includes/plugin.php(208): WP_Hook->apply_filters(false, Array) #3 /membri/wootesting/wp-admin/includes/theme.php(480): apply_filters('themes_api', false, 'theme_informati...', Object(stdClass)) #4 /membri/wootesting/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-status.php(239): themes_api('theme_informati...', Object(stdClass)) #5 /membri/wootesting/wp-content/plugins/woocommerce/packages/woocommerce-rest-api/src/Controllers/Version2/class-wc-rest-system-status-v2-controller.php(1008): WC_Admin_Status::get_latest_ in /membri/.dummy/master/wordpress/wp-content/plugins/altervista/classes/class-av-themes-manager.php on line 84
```
</details>

## This is an overview of the API request that return the error `rest_invalid_signature`.

<details>

```

*** Overview *** 
URL https://public-api.wordpress.com/rest/v1.1/jetpack-blogs/165135189/rest-api/?json=true&path=/wc/v3/orders%26_method%3Dget%26per_page%3D25%26page%3D1%26status%3Dany%26_fields%3Did%2Cparent_id%2Cnumber%2Cstatus%2Ccurrency%2Ccustomer_id%2Ccustomer_note%2Cdate_created_gmt%2Cdate_modified_gmt%2Cdate_paid_gmt%2Cdiscount_total%2Cdiscount_tax%2Cshipping_total%2Cshipping_tax%2Ctotal%2Ctotal_tax%2Cpayment_method_title%2Cline_items%2Cshipping%2Cbilling%2Ccoupon_lines
Method GET
Response Code 400
Request Start Time Aug 20 2019 - 10:15:00
Duration 3s

*** Request Header *** 
Authorization Bearer xyzxyzxyz
User-Agent WooCommerce iOS
Accept application/json
Accept-Language en;q=1.0, it-IT;q=0.9
Accept-Encoding gzip;q=1.0, compress;q=0.5


*** Request Body *** 
- Nothing

*** Response Header *** 
Strict-Transport-Security max-age=15552000
x-ac 2.mxp _dca 
Access-Control-Allow-Origin *
Cache-Control no-cache, must-revalidate, max-age=0
Content-Type application/json
x-hacker Oh, Awesome: Opossum
Server nginx
Date Tue, 20 Aug 2019 08:15:03 GMT
Expires Wed, 11 Jan 1984 05:00:00 GMT


*** Response Body *** 
{
  "error" : "rest_invalid_signature",
  "message" : "La richiesta non è stata mandata correttamente."
}
```
</details>

**Comment by mindgraffiti** [comment]
`rest_invalid_signature` is usually a clue that something isn't syncing correctly with Jetpack. Closing  for now.
