### ISSUE TITLE
Build fails generating credentials if json gem is not installed in the system

### ISSUE THREAD

**Issue by koke** [woocommerce/woocommerce-ios#4067]
**Describe the bug**

We use [bundler](https://bundler.io) to manage our tooling dependencies, and [recommend using rbenv](https://github.com/woocommerce/woocommerce-ios/blob/develop/README.md) to manage the ruby versions.

However, it seems like the GenerateCredentials [build step](https://github.com/woocommerce/woocommerce-ios/blob/f93527378b22b889f1ed6b3db775aaa92be7c997/Scripts/build-phases/generate-credentials.sh) will run in a way where rbenv might not be loaded and not using bundler, so the system ruby is used instead.

This is currently failing for me unless I install the `json` gem in the system ruby with `sudo /usr/bin/gem install json`.

**To Reproduce**
1. Make sure `json` isn't installed system-wide, `sudo /usr/bin/gem uninstall json` if necessary
2. Do a clean build
3. See error

```
>> Loading Secrets /Users/koke/a8c/woocommerce-ios/WooCommerce/../.configure-files/woo_app_credentials.json
>> Generating Credentials /Users/koke/a8c/woocommerce-ios/WooCommerce/DerivedSources/ApiCredentials.swift
/Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/spec_set.rb:89:in `block in materialize': Could not find json-2.5.1 in any of the sources (Bundler::GemNotFound)
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/spec_set.rb:82:in `map!'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/spec_set.rb:82:in `materialize'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/definition.rb:185:in `specs'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/definition.rb:255:in `specs_for'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/definition.rb:237:in `requested_specs'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/runtime.rb:91:in `block in definition_method'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/runtime.rb:20:in `setup'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler.rb:148:in `setup'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/setup.rb:20:in `block in <top (required)>'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/ui/shell.rb:136:in `with_level'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/ui/shell.rb:88:in `silence'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/setup.rb:20:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
>> Generating Credentials /Users/koke/a8c/woocommerce-ios/WooCommerce/DerivedSources/InfoPlist.h
/Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/spec_set.rb:89:in `block in materialize': Could not find json-2.5.1 in any of the sources (Bundler::GemNotFound)
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/spec_set.rb:82:in `map!'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/spec_set.rb:82:in `materialize'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/definition.rb:185:in `specs'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/definition.rb:255:in `specs_for'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/definition.rb:237:in `requested_specs'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/runtime.rb:91:in `block in definition_method'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/runtime.rb:20:in `setup'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler.rb:148:in `setup'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/setup.rb:20:in `block in <top (required)>'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/ui/shell.rb:136:in `with_level'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/ui/shell.rb:88:in `silence'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/setup.rb:20:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
>> Generating Credentials /Users/koke/a8c/woocommerce-ios/WooCommerce/DerivedSources/bash_secrets
/Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/spec_set.rb:89:in `block in materialize': Could not find json-2.5.1 in any of the sources (Bundler::GemNotFound)
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/spec_set.rb:82:in `map!'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/spec_set.rb:82:in `materialize'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/definition.rb:185:in `specs'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/definition.rb:255:in `specs_for'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/definition.rb:237:in `requested_specs'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/runtime.rb:91:in `block in definition_method'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/runtime.rb:20:in `setup'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler.rb:148:in `setup'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/setup.rb:20:in `block in <top (required)>'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/ui/shell.rb:136:in `with_level'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/ui/shell.rb:88:in `silence'
	from /Users/koke/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.15/lib/bundler/setup.rb:20:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
Command PhaseScriptExecution failed with a nonzero exit code

```

**Comment by pmusolino** [comment]
I'm encountering this issue too (Xcode 13.3 and Xcode 13.4)

**Comment by mokagio** [comment]
I'm not sure what the issue was with this, but I'm fairly confident it has been solved since opening?

The app now builds successfully on M1 machines:

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/1218433/177905961-b109a233-c059-45b3-a6b1-b8655a72ec3b.png">

As such, I'm going to close this.
